buttercup/buttercup-core

- package.json
> Symlink error

- doc/api.md
- source/classes/Archive.js
- source/tools/searching.js
- tests/ArchiveTests.js
This PR adds the hasGroup function to the Archive class. It allows for the user to see if a group with the given title exists in the archive.
> Archive.containsGroupWithTitle

- tests/commands/cgrTests.js
- tests/commands/sgaTests.js
This adds full test coverage around the `sga` command.
> Command.sga tests

- source/classes/Westley.js
- source/classes/commands/command.cmm.js
- tests/commands/cmmTests.js
While the command is still in the codebase, it should be under test.
This also covers injecting the callback into the command so that the responsibility is split and so it is testable.
> Tests around comment command

- doc/api.md
- package.json
- source/classes/ButtercupServerAdapter.js
- source/classes/ButtercupServerDatasource.js
- source/classes/TextDatasource.js
- source/classes/WebDAVDatasource.js
- source/module.js
Integration with Buttercup server
> Buttercup server integration

- source/classes/Archive.js
- source/classes/ManagedGroup.js
- tests/ArchiveTests.js
- tests/ManagedGroupTests.js
Upgrades the toObject method in ManagedGroup.
> toObject upgrade

- source/classes/Entry.js
- source/classes/Group.js
- source/decorators/EntryCollection.js
- tests/EntryTests.js
- tests/GroupTests.js
> Fix creating items in trash

- source/module.js
- source/system/NextcloudDatasource.js
- source/system/OwnCloudDatasource.js
> Add Nextcloud integration

- source/system/Entry.js
- source/tools/entry.js
- tests/EntryTests.js
> Make meta calls on entries case insensitive

- source/system/TextDatasource.js
To support mobile environments and others where crypto might be challenging, this feature allows for deferred packaging.
> Separate encryption concerns

- .npmrc
- package.json
- source/system/Archive.js
- source/system/ArchiveManager.js
- source/system/Westley.js
- test/unit/system/ArchiveManager.spec.js
- tests/ArchiveTests.js
- tests/WestleyTests.js
For better integration with tools like Redux, event emitters have been added.
> Event emitters on core components

- source/tools/encoding.js
- tests/EntryTests.js
- tests/encodingTests.js
Empty meta/property/attribute value support.
> Support for empty values

- source/system/Archive.js
- source/system/ArchiveManager.js
- source/system/Westley.js
- source/system/events/AsyncEventEmitter.js
- tests/ArchiveTests.js
> Async emitters

- .gitignore
- package.json
- tests/ModelTests.js
- tests/WestleyTests.js
- tests/_helpers/generator.js
- tests/integration/generatorTests.js
- tests/signingTests.js
Refactor the getRandomCommand function to lower its complexity (eslint complained)
> Setup eslint for the test(s) directories

- source/module.js
- source/system/Entry.js
- source/system/entryFacade.js
- source/tools/entry.js
- source/tools/polyfill.js
- test/unit/system/entryFacade.spec.js
- test/unit/tools/entry.spec.js
- test/unit/tools/polyfill.spec.js
- tests/EntryTests.js
> Facade fixes

- package-lock.json
- source/module.js
- source/system/TextDatasource.js
- source/tools/encoding.js
- source/tools/overridable.js
Still need the last few things to be overridden on the iOS/Android side for this to work on mobile.
> Last crypto overrides

- README.md
Replaced buttercup-pw with buttercup on links
Some of them are have forwards, some not, so, decided to update them
> Replaced buttercup-pw with buttercup on links

- karma.conf.js
- package-lock.json
- source/web/LocalStorageInterface.js
- test/web/Archive.spec.js
- test/web/LocalStorageInterface.spec.js
- test/web/index.js
> Localstorage fix

- .gitignore
- source/node/index.js
- source/node/system/BoxDatasource.js
> Box cloud provider

- source/node/system/archiveManagement/ArchiveManager.js
- source/node/system/archiveManagement/ArchiveSource.js
> Add queuing support to new Archive Manager

- source/node/system/archiveManagement/ArchiveManager.js
- source/node/system/archiveManagement/ArchiveSource.js
Addresses the GUI change-password bug buttercup/buttercup-desktop#575
> Bugfix: ArchiveManager changing password

- package-lock.json
- package.json
- source/node/archiveManagement/ArchiveManager.js
- source/node/archiveManagement/ArchiveSource.js
- source/node/archiveManagement/marshalling.js
- source/node/archiveManagement/offline.js
- test/integration/offline-archivemgr.spec.js
- test/integration/offline-filedatasource.spec.js
- test/integration/offline.spec.js
Offline support for archives: Closes #227
> Offline support

- source/node/archiveManagement/marshalling.js
- test/integration/offline-archivemgr.spec.js
Add readOnly status for archives loaded in offline mode. Closes #227
> Readonly offline

- package-lock.json
- package.json
- source/node/Westley.js
- source/node/Workspace.js
- source/node/archiveManagement/ArchiveManager.js
- source/node/archiveManagement/ArchiveSource.js
- test/integration/ArchiveManager.spec.js
- test/unit/Westley.spec.js
- test/unit/Workspace.spec.js
- test/unit/archiveManagement/ArchiveManager.spec.js
Auto-updating of sources in `ArchiveManager`.
Closes #200 
Fixes #233 - Inigo reference
> Autoupdate

- package-lock.json
- package.json
- source/node/archiveManagement/ArchiveManager.js
- test/integration/ArchiveManager.spec.js
There needs to be an atomic way to interrupt the auto-update cycle to perform changes to the Archive Manager.
> Add auto-update interrupt

- package-lock.json
- package.json
> Update datasources, webdav to fix Seafile issues

- .babelrc
- package-lock.json
- package.json
- source/node/archiveManagement/ArchiveManager.js
- source/node/archiveManagement/ArchiveSource.js
- source/node/tools/entry.js
- webpack.config.js
> Transform runtime (Dropbox issue)

- source/node/Entry.js
See title, opened from comment from @sallar.
> Remove unused var added in PR#239

- source/node/Entry.js
- source/node/commands/DeleteEntryAttributeCommand.js
- source/node/commands/DeleteEntryMetaCommand.js
- source/node/commands/DeleteEntryPropertyCommand.js
- source/node/commands/MoveEntryCommand.js
- source/node/commands/SetEntryAttributeCommand.js
- source/node/commands/SetEntryMetaCommand.js
- source/node/commands/SetEntryPropertyCommand.js
- test/unit/Entry.spec.js
Entry history support so that property/attribute changes can be fetched easily.
> Entry History

- package-lock.json
- source/node/archiveManagement/ArchiveSource.js
Support changing the master password.
> Change password support

- package-lock.json
- package.json
Upgrade webdav for reduced bundle size.
> Upgrade app-env for new webdav

- package.json
- source/datasources/FileDatasource.js
- source/datasources/MemoryDatasource.js
- test/integration/attachments.spec.js
- test/integration/datasources/FileDatasource.spec.js
- webpack.config.js
Attachment support for `FileDatasource`.
Closes #273
> File datasource attachments

- package-lock.json
- package.json
- source/attachments/AttachmentManager.js
- source/datasources/FileDatasource.js
- source/datasources/MemoryDatasource.js
- source/datasources/MyButtercupDatasource.js
- source/datasources/TextDatasource.js
- source/myButtercup/MyButtercupClient.js
- source/myButtercup/symbols.js
- source/tools/attachments.js
- source/tools/buffer.js
- test/integration/attachments.spec.js
- test/web/attachments.spec.js
- webpack.config.js
This PR adds attachment support to the My Buttercup vault source.
> My Buttercup: attachments support

- .travis.yml
> Upgrade travis config

- source/index.common.ts
- source/search/Search.ts
- source/search/searcher.ts
Abstract search portions for facade handling downstream.
> Facade search helpers

- source/index.common.ts
- source/search/BaseSearch.ts
- source/search/VaultEntrySearch.ts
- source/search/VaultFacadeEntrySearch.ts
- test/integration/search/VaultEntrySearch.perf.spec.js
- test/integration/search/VaultEntrySearch.spec.js
- test/integration/search/VaultFacadeEntrySearch.spec.js
- test/web/VaultEntrySearch.spec.js
Upgrades the searching library to support vault facades.
> Facade searching

- package-lock.json
- package.json
- source/core/VaultSource.ts
- test/integration/core/VaultManager.spec.js
- test/integration/core/VaultSource.spec.js
Improvements to the `VaultSource#unlock` method
> Unlock improvement

- .gitignore
- .vscode/settings.json
- package-lock.json
- package.json
- source/core/Group.ts
- source/core/VaultSource.ts
- source/io/VaultFormat.ts
- source/io/VaultFormatA.ts
- source/io/VaultFormatB.ts
- source/io/formatA/commands.ts
- source/io/formatA/merge.ts
- source/io/formatB/conversion.ts
- source/io/formatB/merge.ts
- source/io/formatRouter.ts
- source/types.ts
- test/integration/consistency.spec.js
- test/integration/datasources/WebDAVDatasource.spec.js
- test/integration/formatA.spec.js
- test/integration/saving.spec.js
- test/resources/webdavServer.js
- test/unit/core/Group.spec.js
- test/unit/core/Vault.spec.js
- test/unit/facades/entry.spec.js
- test/unit/io/formatA/VaultComparator.spec.js
- test/unit/io/formatA/describe.spec.js
As per title. Fixes #329 
Also **changes the default format to B**.
> Saving/merging upgrade for Formats (deletion detection)

- source/core/VaultSource.ts
- source/datasources/GoogleDriveDatasource.ts
- source/io/VaultFormatA.ts
- source/io/formatA/merge.ts
- source/io/formatA/tools.ts
- test/integration/consistency.spec.js
Addresses buttercup/buttercup-desktop#1208
> Fix Google Drive upload call

- source/index.common.ts
- source/search/BaseSearch.ts
- source/search/VaultSourceEntrySearch.ts
- test/integration/search/VaultSourceEntrySearch.spec.js
- test/integration/search/helpers.js
New search class for vault sources.
> Vault source entry search
